version: 2

sources:
  - name: erp
    description: 'Essa é a fonte do sistema ERP da northwind com dados de vendas e transações.'
    database: fea24_6
    schema: raw_northwind
    tables:
      - name: employee
        description: 'Tabela com dados de funcionários.'
        columns:
          - name: id
            description: 'Chave primária da tabela funcionários.'
            tests:
              - unique
              - not_null
      - name: product
        description: 'Tabela com dados de produtos.'
      - name: category
        description: 'Tabela com dados de categoria dos produtos.'
      - name: _order_
        description: 'Tabela com dados de pedidos.'
      - name: orderdetail
        description: 'Tabela com dados de detalhamento dos pedidos.'
      - name: customer
        description: 'Tabela com dados de clientes.'
      - name: shipper
        description: 'Tabela com dados de transportadora.'

      - name: supplier
        description: 'Tabela com dados de fornecedores.'

